[package]
name = "csb2json"
description = "TODO"
version = "0.1.0"
edition = "2024"
authors = ["Oleg \"OSA413\" Sokolov", "Skyth"]
repository = "https://github.com/OSA413/SonicAudioTools-rs"
homepage = "https://github.com/OSA413/SonicAudioTools-rs"
license = "MIT"

[dependencies]
sonic-audio-lib-rs = { path = "../sonic-audio-lib-rs" }
common_binary = { path = "../../src_tools/src/common/binary" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.151" }

[lints]
workspace = true